import type { VercelRequest, VercelResponse } from '@vercel/node';
import FormData from 'form-data';
import Mailgun from 'mailgun.js';

export default async function handler(
  req: VercelRequest,
  res: VercelResponse
) {
  // CORS headers - allow requests from Replit frontend
  const allowedOrigins = [
    'https://podcast-growth-agent-goproductmgt.replit.app',
    'https://www.podcastgrowthagent.com',
    'https://podcastgrowthagent.com',
    'http://localhost:3000', // for local testing
  ];

  const origin = req.headers.origin as string;
  
  if (allowedOrigins.includes(origin)) {
    res.setHeader('Access-Control-Allow-Origin', origin);
  }
  
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  res.setHeader('Access-Control-Max-Age', '86400'); // 24 hours

  // Handle preflight OPTIONS request
  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  // Only allow POST requests for actual email sending
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { senderEmail, recipientEmail, episodeData, reportUrl } = req.body; // NEW: Added reportUrl

    // Validate inputs
    if (!senderEmail || !recipientEmail || !episodeData) {
      return res.status(400).json({ 
        error: 'Missing required fields: senderEmail, recipientEmail, episodeData' 
      });
    }

    // Initialize Mailgun
    const mailgun = new Mailgun(FormData);
    const mg = mailgun.client({
      username: 'api',
      key: process.env.MAILGUN_API_KEY || '',
    });

    // NEW: Build report button HTML if reportUrl is provided
    const reportButtonHTML = reportUrl ? `
      <div style="text-align: center; margin: 30px 0;">
        <a href="${reportUrl}" 
           style="display: inline-block; 
                  background: #4CAF50; 
                  color: white; 
                  padding: 15px 30px; 
                  text-decoration: none; 
                  border-radius: 5px; 
                  font-weight: bold;
                  font-size: 16px;">
          📊 View Full Growth Plan
        </a>
        <p style="color: #666; font-size: 14px; margin-top: 10px;">
          Click to see all 5 AI-generated growth strategies
        </p>
      </div>
    ` : '';

    // Email content
    const emailHTML = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2>Your Podcast Growth Report</h2>
        <p>Hi there,</p>
        <p><strong>${senderEmail}</strong> thought you'd find this helpful - a complete growth plan for your podcast episode.</p>
        
        ${reportButtonHTML}
        
        <hr style="margin: 30px 0; border: none; border-top: 1px solid #ddd;">
        <div style="background: #f5f5f5; padding: 20px; border-radius: 8px;">
          <h3>Episode Summary</h3>
          <p>${episodeData.summary || 'Episode analysis included in the full report.'}</p>
        </div>
        <hr style="margin: 30px 0; border: none; border-top: 1px solid #ddd;">
        <p style="color: #666; font-size: 12px;">
          Generated by <a href="https://podcastgrowthagent.com">PodcastGrowthAgent.com</a><br>
          A product of GoProductMgt
        </p>
      </div>
    `;

    // Send email
    const result = await mg.messages.create('mail.goproductmgt.com', {
      from: 'Podcast Growth Agent <reports@mail.goproductmgt.com>',
      to: [recipientEmail],
      'h:Reply-To': senderEmail,
      subject: `${senderEmail.split('@')[0]} shared your Podcast Growth Report`,
      html: emailHTML,
    });

    console.log('Email sent:', result);
    if (reportUrl) {
      console.log('Report URL included:', reportUrl);
    }

    return res.status(200).json({ 
      success: true, 
      message: 'Email sent successfully',
      messageId: result.id 
    });

  } catch (error: any) {
    console.error('Email send error:', error);
    return res.status(500).json({ 
      error: 'Failed to send email',
      details: error.message 
    });
  }
}